;==========================================================
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;  by zamydev
;==========================================================


[colors]
background = #CC0a0a0a
background-alt = #8C0A0A0A
foreground = #f5f5f5
foreground-alt = #33f5f5f5
primary = #fdd835
secondary = #8ABEB7
alert = #A54242
disabled = #707880
;red = #FF5250
;green = #43a047
yellow = #fdd835


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


[bar/mybar]
width = 100%
height = 25
radius = 6
offset-x = 0%
offset-y = 0%
bottom = false
fixed-center = true
radius-top = 0.0
radius-bottom = 0.0
padding = 0

background = ${colors.background}
foreground = ${colors.foreground}
line-size = 2
border-size = 0pt
border-color = #00000000
padding-left = 0
padding-right = 0
module-margin = 1
separator = |
separator-foreground = ${colors.disabled}


modules-left = launcher
modules-center =  workspaces 
modules-right =   date systray  pulseaudio 


cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


;wm-restack = i3

 override-redirect = false

; Fuentes
font-0 = FreeMono;3
font-1 = feather:style=Medium:size=12;3
font-2 = Iosevka Nerd Font:style=Medium:size=12;3
font-3 = Iosevka Nerd Font:style=Medium:size=12;4
font-4 = Iosevka Nerd Font:style=Medium:size=12;4


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;;MODULOS 
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


[module/workspaces]
type = internal/i3

pin-workspaces = true
enable-click = true
enable-scroll = true

format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-focused = 󰷟
label-focused-background = ${colors.background-alt}
label-focused-padding = 1

label-unfocused = ○
label-unfocused-padding = 1

label-urgent = ●
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-visible = •
label-visible-background = #555555
label-visible-padding = 0


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/systray]
type = internal/tray

format-margin = 4pt
tray-spacing = 16pt


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pulseaudio]
type = internal/pulseaudio
sink = alsa_output.pci-0000_03_00.6.analog-stereo
use-ui-max = false
interval = 5

format-volume = <ramp-volume> <label-volume>
format-muted = <ramp-volume> <label-muted>

label-volume = %percentage%% 
label-muted = Muted
label-muted-foreground = 

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

scroll-up = volume+5
scroll-down = volume-5


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date

; Seconds to sleep between updates
interval = 1.0

;;date = %Y-%m-%d%

; Optional time format
time = "󰥔 %I:%M %p"

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
;;date-alt = %A, %d %B %Y
time-alt = 󰨲 %a %d %b 

; Available tags:
;   <label> (default)
format = <label>
format-background = ${yellow}
format-padding = 1

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label = %time%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/launcher]
type = custom/text
content = 

; "content" has the same properties as "format-NAME"
content-background = ${color.background}
content-foreground = ${color.yellow}
content-padding = 1

click-left = /home/zamy/.config/rofi/launchers/type-2/launcher.sh &










[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
